import type { Theme } from "daisyui";

export const THEME_COOKIE_NAME = "theme";

export const THEMES: Theme[] = [
  "light",
  "dark",
  "cupcake",
  "synthwave",
  "retro",
  "cyberpunk",
  "valentine",
  "garden",
  "aqua",
  "lofi",
  "pastel",
  "black",
  "luxury",
  "dracula",
  "lemonade",
  "night",
  "coffee",
  // "bumblebee",
  // "emerald",
  // "corporate",
  // "halloween",
  // "forest",
  // "fantasy",
  // "wireframe",
  // "cmyk",
  // "autumn",
  // "business",
  // "acid",
  // "winter",
  // "dim",
  // "nord",
  "sunset",
];
