name: Production Deployment
env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  TRIGGER_ACCESS_TOKEN: ${{ secrets.TRIGGER_API_KEY }}

on:
  push:
    branches:
      - main

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Install Dependencies
        run: npm install

      # this is so that vercel can build the project
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      # this is so that prisma/trigger.dev can read the .env file
      - name: Pull Vercel Environment To .env
        run: vercel env pull .env --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Prisma Generate
        run: npx prisma generate

      - name: Prisma Migrate Deploy
        run: npx prisma migrate deploy

      - name: Check for changes in app/trigger
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            trigger:
              - 'app/trigger/**'

      - name: Trigger Deploy
        if: steps.filter.outputs.trigger == 'true'
        run: npx trigger.dev@beta deploy

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
